---
# tasks file for ucsdlib.fedora-commons

- name: Create Install Directoory
  file:
    path: '{{ fedora_commons_install }}/fcrepo-{{ fedora_commons_version }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download Fedora Commons
  get_url:
    url: https://github.com/fcrepo4/fcrepo4/releases/download/fcrepo-{{ fedora_commons_version }}/fcrepo-webapp-{{ fedora_commons_version }}-jetty-console.jar
    #remote_src: yes # requires Ansible 2.2
    dest: '{{ fedora_commons_install }}/fcrepo-{{ fedora_commons_version }}/fcrepo-webapp-{{ fedora_commons_version }}-jetty-console.jar'
  environment:
    '{{ fedora_commons_webproxy | default ({}) }}'

- name: Set Default Symlink
  file:
    path: '{{ fedora_commons_install }}/fedora-commons'
    src: 'fcrepo-{{ fedora_commons_version }}'
    state: link
  ignore_errors: '{{ ansible_check_mode }}'
